#!/usr/bin/env bash
# Bash script that will display information about subdomains
display_subdomain() {
  local domain="$1"
  local subdomain="$2"
  local q=$(dig +short "$subdomain.$domain")
  local a=$(dig +short "$subdomain.$domain" | awk 'NR==1 {print toupper($2)}')
  echo "The subdomain $subdomain is a $a record and points to $q"
}
if [ "$4" -eq 2 ]
then
	display_domain "$subdomain.$domain" "$subdomain"
else
	display_subdomain "www.$domain" "www"
	display_subdomain "lb-01.$domain" "lb-01"
	display_subdomain "web-01.$domain" "web-01"
	display_subdomain "web-02.$domain" "web-02"
fi
