#!/usr/bin/env bash
# Install nginx on your web-01
echo -e "Updating the system"
apt-get update
echo -e "Installing nginx"
apt-get install -y nginx
sed -i 's/^\s*listen\s*\(.*\)/\1/' /etc/nginx/sites-available/default
service nginx restart
echo "Hello World" > /var/www/html/index.html
echo "Nginx installation complete"
