#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo bash -c 'cat << EOF > /etc/nginx/conf.d/custom_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    add_header X-Served-By $HOSTNAME;
}
EOF'
sudo systemctl restart nginx
