#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a
# compressed archive out of it
if [ -z "$1" ]; then
        echo "Usage: $0 <mysql_password>"
        exit 1
fi
# mysql dump file name
dump_file="backup.sql"
# generate mysql dump
mysqldump -u root -p"$1" --all-databases > "$dump_file"
# check if the mysql dump is created
if [ $? -ne 0 ]; then
        echo "Error: MySQL dump failed"
        exit 1
fi
# if dump file is created
if [ ! -s "$dump_file" ]; then
        echo "Error: dump file is not created or is empty"
        exit 1
fi
# compressed archive name format
archive_name="$(date +"%d-%m-%Y").tar.gz"
# compress the mysql dump into archive
tar -czf "$archive_name" "$dump_file"
# check if the compression is successful
if [ $? -ne 0 ]; then
        echo "Error: Compression failed"
        exit 1
fi
# remove the mysql dump file
rm "$dump_file"
echo "Backup completed successfully: $archive_name"
