#!/usr/bin/env bash
# Bash script with the minimum number of commands to automate your fix
nginx -t
if ! command -v nginx &> /dev/null; then
	echo "Nginx is not installed"
	exit 1
fi
if curl -s 0:80 &> /dev/null; then
        echo "Nginx is already listening on port 80"
        exit 0
fi
if systemctl is-active --quiet nginx; then
        echo "Nginx is already running but not listening to port 80"
else
        echo "Nginx is starting..."
        service nginx start
fi
echo "Configuring Nginx to listen on port 80..."
sed -i 's/^listen\s*80;$/listen 80 default_server;/g' /etc/nginx/sites-available/default
echo "Reloding Nginx..."
service nginx reload
if curl -s 0:80 &> /dev/null; then
        echo "Nginx is now listening on port 80"
else
        echo "Failed to configure Nginx to listen on port 80"
        exit 1
fi
exit 0
