#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
if [ -f "/.dockerenv/" ]; then
	echo "This is running inside Docker. Configuration"
else
	echo "This should be run inside Docker. Exiting"
	exit 1
fi
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
echo "Host file configured"
