#!/usr/bin/env bash
# Bash script that configures
# configure nginx to run as nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
# update nginx default sites confg file
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart
# check if nginx is running
ps auxff | grep ngin[x]
# check if nginx is listening on port 8080
nc -z 0 8080 ; echo $?
