#!/usr/bin/env bash
# nginx config file for gunicorn

server {
    listen 80;
    server_name 54.236.41.226;

    location = /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://localhost:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  # location is the page
  location = /airbnb-onepage/ {
    # procy pass
    proxy_pass http://localhost:5000;
    # proxy set header is host
    proxy_set_header Host "$host";
    # peoxy set header ip
    proxy_set_header X-Real-IP "$remote_adr";
    # proxy set header x forwarded
    proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for";
  }
}
