#!/usr/bin/env bash
# config file for nginx api

server {
    listen 80;
    server_name 54.236.41.226;

    location /api/ {
        proxy_pass http://localhost:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
