#!/usr/bin/env bash
# config file 5
server {
    listen 80;
    server_name 54.236.41.226;

    location / {
        proxy_pass http://localhost:5003;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        alias /root/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
    }
}
